name: ci

on: [push, pull_request]

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20, 22, 23]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: ./.tap/report/lcov.info
          flag-name: run-${{ join(matrix.*, '-') }}
          format: lcov
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
